config/routes.rb
Geekgifts::Application.routes.draw do
  devise_for :admins

  mount RailsAdmin::Engine => '/wxtse', :as => 'rails_admin'
  root :to=>"home#index"
  get '/about' => "static_pages#about", :as=>:about
  get '/gift-for-geeks/:slug' => "ideas#slug", :as=>:idea_slug

  match '/tag/:id/add' => "misc_admin_idea#add_tag_idea", :as=>:add_tag_idea
  post '/tag/:id/post' => "misc_admin_idea#post_tag_idea", :as=>:post_tag_idea
  match '/gifts-for/:tag' => "tag#gifts_for", :as=>:gifts_for_tag

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/affiliate_link.rb
class AffiliateLink < ActiveRecord::Base
  attr_accessible :company, :html
  belongs_to :idea
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  #attr_accessible :affiliate_url, :meta_description, :price, :seller_name, :title, :active, :counter_cache, :small_image, :large_image, :affiliate_url, :impressions, :small_image_cache, :large_image_cache
  attr_protected
  #Fuck mass assignment!
  mount_uploader :small_image, ImageUploader
  mount_uploader :large_image, ImageUploader
  acts_as_taggable
  has_many :affiliate_links

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @ideas = Idea.where( :active=>true ).shuffle
    @title = "Total Geek Stuff::Cool Gift Ideas and stuff for Geeks"
    @meta_description = "Cool gift ideas for that special geek in your life. Or, cool stuff for geeks to buy themselves! Add these geek items to your collection. Get ideas on the latest geek items."
    @meta_keywords = "Gifts, Geeks, nerds, nerd, geek, techie, cool gift, cool, gifts for geeks, geek gifts, geek gift"
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def slug
    @idea = Idea.find_by_slug( params[:slug] )
    @title = "Total Geek Stuff | Gift for Geeks | #{@idea.title}"
    @meta_description = "Get #{@idea.title} a cool geek gift for that special geek in your life or just buy it yourself."
  end
end

app/controllers/misc_admin_idea_controller.rb
class MiscAdminIdeaController < ApplicationController
  before_filter :authenticate_admin!

  def add_tag_idea
    @idea = Idea.find( params[:id] )
    @tags = @idea.tags.map { |t| t.name }
    #@tags = []
    #@idea.tags.select { |t| @tags << t.name }
  end

  def post_tag_idea
    if ( params[:tags].present? && params[:id].present? )
      # Add this to the tags thing
      idea = Idea.find(params[:id])
      idea.tag_list = params[:tags]
      idea.save
      render :text => "Added tags: #{ params[:tags]} to Idea with title: #{ idea.title}", :layout => nil and return
    end

    render :text => "Couldn't save oh-oh"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
caches_page :about

  def about
    @title = "Total Geek Stuff::About Us - Cool Gift Ideas and stuff for Geeks"
    @meta_description = "Learn more about Total Geek Stuff and why this website was created. Meet a very geeky dude."
    @meta_keywords = "about us, description, sam contapay, sam, geek, about a geek"
  end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController

  def gifts_for
    #display all the gifts with a particular tag
    @ideas = Idea.tagged_with( params[:tag], :any=>true )
    @title = "Total Geek Stuff | Gift Ideas and stuff for #{params[:tag]}"
    @meta_description = "Gift Ideas for the geek in your life. These are gift ideas for #{params[:tag]}. Visit the home page for more gift ideas."
    @meta_keywords = "geek stuff,geek gifts,gifts for #{params[:tag]},geek,geek items"
    render :template => 'home/index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/misc_admin_idea_helper.rb
module MiscAdminIdeaHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/home/_affiliate.html.erb
<div id="affiliate_box" style="max-width: 320px;">
<fieldset style="border-style: none;">
    <legend style="color:blue;font-weight:bold;"><%= affiliate_link.company %></legend>
    <table style="border-collapse: collapse;">
        <tr>
            <td><%= affiliate_link.html.html_safe %></td>
        </tr>
    </table>
</fieldset>

</div>

app/views/home/_header.html.erb
<div class="tagline" style="text-align: right;"><h1>What Geeks Want. Cool Gift Ideas for Geeks.</h1></div>
<div class="maintitle" style="text-align: right">Total Geek Stuff</div>
<p></p>
<div id="topbar" style="display: block;">
    <ul>
      <li><%=link_to "Home", root_path %></li>
      <li><%= link_to "About Us", about_path %></li>
    </ul>
</div>

app/views/home/_idea.html.erb
<div class="idea">
  <h3><%= idea.tag_line %></h3>
  <h2><%= idea.title %></h2>
  <div id="imgcontainer" style="width: 300px; height: 300px;">
  <%= image_tag idea.small_image.url, :alt=>idea.title %>
  </div>
  <%= idea.description.html_safe %>
  <br /><br />
  <%= render :partial => 'home/affiliate', :collection => idea.affiliate_links, :as=>:affiliate_link %>

  <div style="float: right; display: block;">
    <p><%= link_to "Read More...", idea_slug_path(:slug=>idea.slug) %></p>
  </div>

</div>

app/views/home/index.html.erb
<div id="entirepage">
    <%= render :partial=>"home/header" %>
    <br />

    <div id="ideas">
        <%= render :partial=>"home/idea", :collection=>@ideas %>
    </div>

</div> <!-- end of page -->




<script type="text/javascript" src="http://wms.assoc-amazon.com/20070822/US/js/link-enhancer-common.js?tag=totgeestu-20">
</script>
<noscript>
    <img src="http://wms.assoc-amazon.com/20070822/US/img/noscript.gif?tag=totgeestu-20" alt="" />
</noscript>

app/views/ideas/_affiliate_link.html.erb
<p>
Buy From <%=affiliate_link.company %><br>
<%= affiliate_link.html.html_safe %>
</p>

app/views/ideas/slug.html.erb
<div id="entirepage">
    <%= render :partial=>"home/header" %>
    <br />

<div class="idea" style="position: relative;">
    <h3 style="float: left;"><%= @idea.tag_line %></h3><br/>
    <h1 style="margin: 0;"><%= @idea.title %></h1>
    <br />
    <%= image_tag @idea.small_image.url, :style=>"float: left; margin-right: 5px;", :alt=>@idea.title %>
    <div id="article" style="float: left; width: 340px; padding: 3px;">
      <%= @idea.blog.html_safe %>
    </div>
    <div style="float: right; width: 305px; border-left: 1px dashed #d3d3d3; padding-left: 5px;">
        <div id="sharing">
          <a href="http://twitter.com/share?url=<%= idea_slug_url(:slug=>@idea.slug) %>&text=Check out <%= @idea.title%> on Total Geek Stuff. Cool stuff and gifts for geeks #totalgeekstuff" target="_blank" rel="nofollow"><%= image_tag "Twitter-icon.png" %></a>
        </div>
        <%= render :partial=>"ideas/affiliate_link", :collection=>@idea.affiliate_links %>
        <%= link_to "View more geek stuff", root_path, :class=>"blue-button" %>
        <p>
          <div id="slug_tags">
            <br />
            <p>Tags</p>
            <%
                @idea.tags.each do |tag|
                %>
                    <%= link_to "| #{tag.name}", gifts_for_tag_path(:tag=>tag.name) %>
                <%
                end
            %> |
          </div>
        </p>
    </div>
</div>



</div> <!-- END OF PAGE-->

<script type="text/javascript" src="http://wms.assoc-amazon.com/20070822/US/js/link-enhancer-common.js?tag=totgeestu-20">
</script>
<noscript>
    <img src="http://wms.assoc-amazon.com/20070822/US/img/noscript.gif?tag=totgeestu-20" alt="" />
</noscript>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <% if not @meta_description.blank? %>
    <meta name="description" content="<%= @meta_description%>" />
  <% end %>
  <meta name="author" content="Sam Contapay" />
  <% if not @meta_keywords.blank? %>
    <meta name="keywords" content="<%= @meta_keywords %>" />
  <% end %>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-33880158-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>

<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/misc_admin_idea/add_tag_idea.html.erb
<p>Enter a string of tags that are comma seperated and any new tags override the old tags</p>
<p>Current tags: <%= @tags.join ',' %></p>
<%= form_tag(:controller=>"misc_admin_idea", :action=>"post_tag_idea", :method=>:post ) do %>
    <%=  label_tag(:label, "Tag for #{@idea.title}") %>
    <%= text_field_tag(:tags, nil, :size=>80) %>
    <%= submit_tag("Submit") %>
<% end %>

app/views/static_pages/about.html.erb
<div id="entirepage">
    <%= render :partial=>"home/header" %>
    <br />
    <h1>About Us</h1>

    <div id="content" style="width: 620px;">
        <div>
        <p>First there is no us. There is just a me, my name is Sam, pleasure to meet you. I am a self proclaimed geek I make a living
        as a computer programmer at a San Francisco, CA based startup. I started my tech career at a young age with an unknown computer at the age
        of 10. I then moved onto game systems: Odyssey 2, Colecovision and then the ADAM which was an attachment to the Colecovision with a
        daisy wheel printer! So many knight playing Dragon Age on that which was on a cassette.</p>

        <p>From there I started building computers and buying any computer books I could on programming. I focused on C and C++ and then
        in my professional career I have programmed in: Objective-C, Visual Basic 6, VBA, JAVA, PHP, Ruby, Python, HTML, CSS, Javascript. In
        my free time I like to code up projects you can find me on Github <a href="http://www.github.com/madgeekfiend">http://www.github.com/madgeekfiend</a>.</p>

        <p>I am also a gamer, I still play games at the age of almost 40 (Damn I'm getting old). I have several level 85s on World of Warcraft and
        I play a plethora of games and own a variety of game systems. I will always be a PC gamer it is just much easier playing FPS and
        strategy games with a mouse and keyboard.</p>

        <p>This site is just a collection of stuff I would like, or I have bought. I wish I can afford to buy them all and give you my actual hands on experience
        but I'm not rich. Feel free to send me an email about this site, comments, questions, or some more geek stuff at <a href="mailto: totalgeek@totalgeekstuff.com">totalgeek@totalgeekstuff.com</a>. Or,
        follow me on twitter.</p>

        <p><em>My name is Sam and I'm a geek!</em></p>
        </div>

        <div id="social">
          <a href="https://twitter.com/themorningdump" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @themorningdump</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>
    </div>

</div> <!-- end of page -->